export const APPS = [
  {
    slug: 'vaultcap',
    name: 'VaultCap',
    symbol: '◆',
    category: 'Finance & Identity',
    ver: '4.3.5',
    tagline: 'Everything you own. Encrypted.',
    pitch: 'Private vault for money, identity, and documents — encrypted on your phone before anything is saved.',
    hook: 'Bank-grade encryption. No account. No server. Just your vault.',
    accent: '#5b8dee',
    accent2: '#3d5a9e',
    bg: '#070b14',
    vibe: 'vault',
    url: 'https://shamikhahmed.github.io/VaultCap/',
    pitchUrl: 'https://shamikhahmed.github.io/VaultCap/pitch.html',
    icon: 'assets/icons/vaultcap.svg',
    mark: 'assets/marks/vaultcap.svg',
    screenshot: 'assets/screenshots/vaultcap.png',
    highlights: ['AES-256-GCM', '120+ banks', 'Family vault', 'Zakat engine'],
    features: ['AES-256-GCM vault with local PIN', '120+ PK, UK, UAE bank import', 'Family profiles — each encrypted', 'Zakat engine from real holdings'],
  },
  {
    slug: 'pulsecap',
    name: 'PulseCap',
    symbol: '◇',
    category: 'Performance',
    ver: '4.7.3',
    tagline: 'Train with intention.',
    pitch: 'Performance OS for lifters — 300+ exercises, body intelligence, recovery readiness, Smart Coach offline.',
    hook: 'Your training log, your PRs, your recovery — on your phone.',
    accent: '#00f2ff',
    accent2: '#0e7bff',
    bg: '#0a0a0f',
    vibe: 'kinetic',
    url: 'https://shamikhahmed.github.io/PulseCap/',
    pitchUrl: 'https://shamikhahmed.github.io/PulseCap/pitch.html',
    icon: 'assets/icons/pulsecap.svg',
    mark: 'assets/marks/pulsecap.svg',
    screenshot: 'assets/screenshots/pulsecap.png',
    highlights: ['300+ exercises', 'Body map', 'Smart Coach', 'PR tracking'],
    features: ['300+ exercises with muscle mapping', 'Smart Coach reads your history offline', 'Recovery readiness — no wearable', 'PR tracking and body map'],
  },
  {
    slug: 'prismcap',
    name: 'PrismCap',
    symbol: '✦',
    category: 'Play',
    ver: '3.0',
    tagline: '38 games. One phone. Zero Wi‑Fi.',
    pitch: 'Party arcade on your phone — 38 pass-and-play games, achievements, daily challenges. No accounts, no ads.',
    hook: 'The living room becomes an arcade. Pass the phone, not your data.',
    accent: '#c77dff',
    accent2: '#ff2d78',
    bg: '#0a0014',
    vibe: 'arcade',
    url: 'https://shamikhahmed.github.io/PrismCap/',
    pitchUrl: 'https://shamikhahmed.github.io/PrismCap/pitch.html',
    icon: 'assets/icons/prismcap.svg',
    mark: 'assets/marks/prismcap.svg',
    screenshot: 'assets/screenshots/prismcap.png',
    highlights: ['38 games', 'Pass & Play', 'Daily challenges', 'XP system'],
    features: ['38 game engines — each built from scratch', 'Pass & Play couch multiplayer', 'Daily challenges without a server', 'XP + achievements stay local'],
  },
  {
    slug: 'steadycap',
    name: 'SteadyCap',
    symbol: '○',
    category: 'Recovery',
    ver: '2.8',
    tagline: 'Recovery is a system. Not a streak.',
    pitch: 'Recovery app — habits, medicines, journal triggers, craving forecasts, 5-phase SOS. Serious and warm.',
    hook: 'When it matters, SteadyCap is one tap from your home screen.',
    accent: '#c9652b',
    accent2: '#2f8e88',
    bg: '#1a110e',
    vibe: 'clinical',
    url: 'https://shamikhahmed.github.io/SteadyCap/',
    pitchUrl: 'https://shamikhahmed.github.io/SteadyCap/pitch.html',
    icon: 'assets/icons/steadycap.svg',
    mark: 'assets/marks/steadycap.svg',
    screenshot: 'assets/screenshots/steadycap.png',
    highlights: ['Trigger forecast', '5-phase SOS', 'Medicine tracker', 'Journal'],
    features: ['Trigger forecast from your journal patterns', '5-phase SOS crisis flow — offline', 'Medicine tracker on-device only', 'Habit milestones without streak guilt'],
  },
  {
    slug: 'ledgercap',
    name: 'LedgerCap',
    symbol: '▣',
    category: 'Wealth',
    ver: '1.4',
    tagline: 'Pakistani wealth. One ledger.',
    pitch: 'Wealth tracker for Pakistani investors — PSX, Meezan funds, Zakat, IPO watch, net worth in PKR.',
    hook: 'PSX, funds, Zakat, net worth — terminal-grade, phone-native, private.',
    accent: '#f59e0b',
    accent2: '#0ecb81',
    bg: '#0b0e11',
    vibe: 'terminal',
    url: 'https://shamikhahmed.github.io/LedgerCap/',
    pitchUrl: 'https://shamikhahmed.github.io/LedgerCap/pitch.html',
    icon: 'assets/icons/ledgercap.svg',
    mark: 'assets/marks/ledgercap.svg',
    screenshot: 'assets/screenshots/ledgercap.png',
    highlights: ['PSX', 'Meezan funds', 'Zakat', 'IPO tracker'],
    features: ['PSX holdings and transaction log', 'Meezan Islamic fund positions', 'Zakat from actual holdings', 'Net worth in PKR — one terminal'],
  },
  {
    slug: 'deeponycap',
    name: 'DeePonyCap',
    symbol: '♡',
    category: 'Collection',
    ver: '3.0',
    tagline: 'Every pony. One stable.',
    pitch: 'My Little Pony collection tracker — G1 through G5, photo shelves, wishlists. COPPA-safe for kids.',
    hook: 'Open the stable. No ads. No chat. No cloud.',
    accent: '#c4367a',
    accent2: '#8b5cf6',
    bg: '#d4a0b8',
    vibe: 'toy',
    light: true,
    url: 'https://shamikhahmed.github.io/DeePonyCap/',
    pitchUrl: 'https://shamikhahmed.github.io/DeePonyCap/pitch.html',
    icon: 'assets/icons/deeponycap.svg',
    mark: 'assets/marks/deeponycap.svg',
    screenshot: 'assets/screenshots/deeponycap.png',
    highlights: ['G1–G5', 'Photo shelves', 'Wishlists', 'COPPA-safe'],
    features: ['G1–G5 catalog for small hands', 'Photo shelves in IndexedDB — never uploaded', 'Wishlist tiers: want, need, grail', 'Achievement bubbles — no ads'],
  },
  {
    slug: 'scentcap',
    name: 'ScentCap',
    symbol: '◌',
    category: 'Lifestyle',
    ver: '1.2.1',
    tagline: 'Your wardrobe. Finally organized.',
    pitch: 'Fragrance OS — catalog bottles, log wears, layer with intention, daily picks from weather and occasion.',
    hook: 'The only wardrobe that remembers what you wore.',
    accent: '#c9a87c',
    accent2: '#8b6914',
    bg: '#1a1614',
    vibe: 'luxury',
    url: 'https://shamikhahmed.github.io/ScentCap/',
    pitchUrl: 'https://shamikhahmed.github.io/ScentCap/pitch.html',
    icon: 'assets/icons/scentcap.svg',
    mark: 'assets/marks/scentcap.svg',
    screenshot: 'assets/screenshots/scentcap.png',
    highlights: ['Wardrobe', 'Smart Advisor', 'Layering', 'Wear log'],
    features: ['Today dashboard with weather picks', 'Wardrobe catalog + level tracking', 'Smart Advisor — rules-based, not cloud AI', 'Layering Lab for saved combos'],
  },
  {
    slug: 'soulcap',
    name: 'SoulCap',
    symbol: '✧',
    category: 'Wellness',
    ver: '1.0',
    tagline: 'Know yourself. Grow yourself.',
    pitch: 'AI emotional wellness with a Living Mind Model — evolving psychological profile, clinical safety tiers, nothing sold to advertisers.',
    hook: 'The only wellness app that remembers who you are becoming.',
    accent: '#7c6ff7',
    accent2: '#a78bfa',
    bg: '#0f0f1a',
    vibe: 'soul',
    wip: true,
    url: 'https://github.com/shamikhahmed/SoulCap',
    pitchUrl: 'https://github.com/shamikhahmed/SoulCap',
    icon: 'assets/icons/soulcap.svg',
    mark: 'assets/marks/soulcap.svg',
    screenshot: '',
    highlights: ['Living Mind Model', '4-tier safety', 'Session memory', 'Clinical guardrails'],
    features: ['Living Mind Model updates every session', '4-tier clinical safety system', 'Crisis flows with professional escalation', 'Private by design — your mind stays yours'],
  },
  {
    slug: 'travelcap',
    name: 'TravelCap',
    symbol: '✈',
    category: 'Travel',
    ver: '0.2.1',
    tagline: 'Your trip. One OS.',
    pitch: 'TravelOS — trips, packing, flights, hotels, budget, passport stats, and smart assistant. Local-first PWA.',
    hook: 'Before, during, after — every mile on your device.',
    accent: '#007aff',
    accent2: '#38bdf8',
    bg: '#051a33',
    vibe: 'travel',
    wip: true,
    url: 'https://github.com/shamikhahmed/TravelCap',
    pitchUrl: 'https://github.com/shamikhahmed/TravelCap',
    icon: 'assets/icons/travelcap.svg',
    mark: 'assets/marks/travelcap.svg',
    screenshot: '',
    highlights: ['Trip OS', 'Packing', 'Passport map', 'Offline PWA'],
    features: ['Dashboard readiness + countdown widgets', 'Smart packing by weather and profile', 'Document vault with OCR expiry', 'Family profiles and budget tracking'],
  },
  {
    slug: 'auracap',
    name: 'AuraCap',
    symbol: '◎',
    category: 'Productivity',
    ver: '5.0.6',
    tagline: 'Your Apple setup. Understood.',
    pitch: 'Imports your real app list, scores your ecosystem, designs layouts across iPhone, iPad, Mac — nothing uploaded.',
    hook: 'Aura Score. Digital DNA. Design studio. All on your device.',
    accent: '#4f6ef7',
    accent2: '#7b5ea7',
    bg: '#050507',
    vibe: 'apple',
    url: 'https://shamikhahmed.github.io/AuraCap/',
    pitchUrl: 'https://shamikhahmed.github.io/AuraCap/pitch.html',
    icon: 'assets/icons/auracap.svg',
    mark: 'assets/marks/auracap.svg',
    screenshot: 'assets/screenshots/auracap.png',
    highlights: ['16 modules', 'Digital DNA', 'Aura Score', 'Widget lab'],
    features: ['16 modules — DNA, Import, Designer, Widgets', 'Digital DNA from your real app list', 'Aura Score for setup intentionality', '42+ wallpapers + lockscreen builder'],
  },
];

export function wipBadgeHTML() {
  return '<span class="wip-badge">WIP</span>';
}

/** Capricorn OS task list — desktop Tasks widget + iOS Today (single source). */
export const TASKS = [
  { label: 'Follow on GitHub', tag: 'Connect', detail: '@shamikhahmed', action: 'social', social: 'github' },
  { label: 'Follow on X', tag: 'Connect', detail: '@capricornsys', action: 'social', social: 'x' },
  { label: 'Follow on Instagram', tag: 'Connect', detail: '@capricornsys', action: 'social', social: 'instagram' },
  { label: 'Follow on LinkedIn', tag: 'Connect', detail: 'Capricorn Systems', action: 'social', social: 'linkedin' },
  { label: 'Follow on YouTube', tag: 'Connect', detail: '@capricornsys', action: 'social', social: 'youtube' },
  { label: 'Follow on TikTok', tag: 'Connect', detail: '@capricornsys', action: 'social', social: 'tiktok' },
  { label: 'Follow on Threads', tag: 'Connect', detail: '@capricornsys', action: 'social', social: 'threads' },
  { label: 'Net worth', tag: 'VaultCap', detail: 'Zakat due', action: 'app', slug: 'vaultcap' },
  { label: 'Push session', tag: 'PulseCap', detail: 'Recovery 87', action: 'app', slug: 'pulsecap' },
  { label: 'PSX review', tag: 'LedgerCap', detail: 'ENGRO ▲', action: 'app', slug: 'ledgercap' },
  { label: 'Evening dose', tag: 'SteadyCap', detail: 'Day 47', action: 'app', slug: 'steadycap' },
  { label: 'Log wear', tag: 'ScentCap', detail: 'Oud Wood', action: 'app', slug: 'scentcap' },
  { label: 'Cipher Duel', tag: 'PrismCap', detail: 'Lv 4', action: 'app', slug: 'prismcap' },
  { label: 'G4 shelf', tag: 'DeePonyCap', detail: '41/50', action: 'app', slug: 'deeponycap' },
  { label: 'Pack BCN', tag: 'TravelCap', detail: '12 days', action: 'app', slug: 'travelcap' },
  { label: 'Soul check-in', tag: 'SoulCap', detail: 'LMM sync', action: 'app', slug: 'soulcap' },
  { label: 'DNA scan', tag: 'AuraCap', detail: 'Score 84', action: 'app', slug: 'auracap' },
];

export const SYSTEM = {
  name: 'Capricorn OS',
  version: '∞.1',
  build: 'sovereign-2026',
  founder: 'Shamikh Ahmed',
  tagline: 'Software that lives on your device.',
  pitch: 'Capricorn Systems builds sovereign software — ten apps for finance, performance, recovery, wealth, travel, and wellness. Encrypted on your phone. No cloud rent. No analytics daemon. One founder. Your rules.',
  logo: 'assets/logo.svg',
};

/** Social accounts — set `url` when live; empty = coming soon toast */
export const SOCIAL = [
  { id: 'github', label: 'GitHub', handle: '@shamikhahmed', url: 'https://github.com/shamikhahmed' },
  { id: 'x', label: 'X', handle: '@capricornsys', url: '' },
  { id: 'instagram', label: 'Instagram', handle: '@capricornsys', url: '' },
  { id: 'linkedin', label: 'LinkedIn', handle: 'Capricorn Systems', url: '' },
  { id: 'youtube', label: 'YouTube', handle: '@capricornsys', url: '' },
  { id: 'tiktok', label: 'TikTok', handle: '@capricornsys', url: '' },
  { id: 'threads', label: 'Threads', handle: '@capricornsys', url: '' },
];
