/** Capricorn OS catalog — versions synced from each app VERSION.json (HUB-P0-01). */
export const APPS = [
  {
    slug: 'vaultcap',
    name: 'VaultCap',
    symbol: '◆',
    category: 'Finance & Identity',
    ver: '5.2.1',
    tagline: 'Everything you own, encrypted on your device.',
    pitch: 'Private vault for money, identity, and documents — encrypted on your phone before anything is saved.',
    hook: 'Bank-grade encryption. No account. No server. Just your vault.',
    accent: '#5b8dee',
    accent2: '#3d5a9e',
    bg: '#070b14',
    vibe: 'vault',
    demo: true,
    url: 'https://shamikhahmed.github.io/VaultCap/',
    pitchUrl: 'https://shamikhahmed.github.io/VaultCap/pitch.html',
    github: 'https://github.com/shamikhahmed/VaultCap',
    icon: 'assets/icons/vaultcap.svg',
    mark: 'assets/marks/vaultcap.svg',
    screenshot: 'assets/screenshots/vaultcap.png',
    highlights: ['AES-256-GCM', 'Banks', 'Family vault', 'Zakat'],
    features: ['AES-256-GCM vault with local PIN', 'Bank import on device', 'Family profiles — each encrypted', 'Zakat from real holdings'],
  },
  {
    slug: 'pulsecap',
    name: 'PulseCap',
    symbol: '◇',
    category: 'Performance',
    ver: '6.43.0',
    tagline: 'Plan, log and track your training. Works offline.',
    pitch: 'Training log, recovery readiness, and Smart Coach offline — no wearable required.',
    hook: 'Your training log, your PRs, your recovery — on your phone.',
    accent: '#00f2ff',
    accent2: '#0e7bff',
    bg: '#0a0a0f',
    vibe: 'kinetic',
    demo: true,
    url: 'https://shamikhahmed.github.io/PulseCap/',
    pitchUrl: 'https://shamikhahmed.github.io/PulseCap/pitch.html',
    github: 'https://github.com/shamikhahmed/PulseCap',
    icon: 'assets/icons/pulsecap.svg',
    mark: 'assets/marks/pulsecap.svg',
    screenshot: 'assets/screenshots/pulsecap.png',
    highlights: ['Workouts', 'Recovery', 'Smart Coach', 'PRs'],
    features: ['Exercise library with muscle mapping', 'Smart Coach reads your history offline', 'Recovery readiness — no wearable', 'PR tracking'],
  },
  {
    slug: 'prismcap',
    name: 'PrismCap',
    symbol: '✦',
    category: 'Play',
    ver: '4.5.0',
    tagline: 'Party games for one phone, passed around the room.',
    pitch: 'Pass-and-play party games on your phone. No accounts, no ads.',
    hook: 'The living room becomes an arcade. Pass the phone, not your data.',
    accent: '#c77dff',
    accent2: '#ff2d78',
    bg: '#0a0014',
    vibe: 'arcade',
    demo: true,
    url: 'https://shamikhahmed.github.io/PrismCap/',
    pitchUrl: 'https://shamikhahmed.github.io/PrismCap/pitch.html',
    github: 'https://github.com/shamikhahmed/PrismCap',
    icon: 'assets/icons/prismcap.svg',
    mark: 'assets/marks/prismcap.svg',
    screenshot: 'assets/screenshots/prismcap.png',
    highlights: ['Pass & Play', 'Offline', 'XP', 'Achievements'],
    features: ['Pass-and-play couch multiplayer', 'Daily challenges without a server', 'XP and achievements stay local', 'No accounts, no ads'],
  },
  {
    slug: 'steadycap',
    name: 'SteadyCap',
    symbol: '○',
    category: 'Recovery',
    ver: '2.5.1',
    tagline: 'Routines, medicines and support for recovery.',
    pitch: 'Habits, medicines, journal, and SOS — serious and warm, on your device.',
    hook: 'When it matters, SteadyCap is one tap from your home screen.',
    accent: '#c9652b',
    accent2: '#2f8e88',
    bg: '#1a110e',
    vibe: 'clinical',
    demo: true,
    url: 'https://shamikhahmed.github.io/SteadyCap/',
    pitchUrl: 'https://shamikhahmed.github.io/SteadyCap/pitch.html',
    github: 'https://github.com/shamikhahmed/SteadyCap',
    icon: 'assets/icons/steadycap.svg',
    mark: 'assets/marks/steadycap.svg',
    screenshot: 'assets/screenshots/steadycap.png',
    highlights: ['SOS', 'Medicines', 'Journal', 'Routines'],
    features: ['SOS crisis flow — offline', 'Medicine tracker on-device only', 'Journal and check-ins', 'No streak guilt'],
  },
  {
    slug: 'ledgercap',
    name: 'LedgerCap',
    symbol: '▣',
    category: 'Wealth',
    ver: '3.57.0',
    tagline: 'Track your PSX stocks and mutual funds in one place.',
    pitch: 'PSX holdings, funds, and net worth in PKR — Worker-backed prices, private on your phone.',
    hook: 'PSX, funds, net worth — phone-native, private.',
    accent: '#f59e0b',
    accent2: '#0ecb81',
    bg: '#0b0e11',
    vibe: 'terminal',
    demo: true,
    url: 'https://shamikhahmed.github.io/LedgerCap/',
    pitchUrl: 'https://shamikhahmed.github.io/LedgerCap/pitch.html',
    github: 'https://github.com/shamikhahmed/LedgerCap',
    icon: 'assets/icons/ledgercap.svg',
    mark: 'assets/marks/ledgercap.svg',
    screenshot: 'assets/screenshots/ledgercap.png',
    highlights: ['PSX', 'Funds', 'PKR', 'Research'],
    features: ['PSX holdings and transaction log', 'Mutual fund positions', 'Net worth in PKR', 'Research tools — not investment advice'],
  },
  {
    slug: 'deeponycap',
    name: 'DeePonyCap',
    symbol: '♡',
    category: 'Collection',
    ver: '3.8.0',
    tagline: 'Track your collection, shelves and wishlist.',
    pitch: 'Photo shelves, wishlists, and series you define. Private, offline, no ads.',
    hook: 'Your collection on your phone. No ads. No cloud.',
    accent: '#c4367a',
    accent2: '#8b5cf6',
    bg: '#d4a0b8',
    vibe: 'toy',
    light: true,
    demo: true,
    url: 'https://shamikhahmed.github.io/DeePonyCap/',
    pitchUrl: 'https://shamikhahmed.github.io/DeePonyCap/pitch.html',
    github: 'https://github.com/shamikhahmed/DeePonyCap',
    icon: 'assets/icons/deeponycap.svg',
    mark: 'assets/marks/deeponycap.svg',
    screenshot: 'assets/screenshots/deeponycap.png',
    highlights: ['Shelves', 'Wishlist', 'Series', 'Private'],
    features: ['User-defined series', 'Photo shelves in IndexedDB', 'Wishlist tiers', 'Independent — not affiliated with any toy company'],
  },
  {
    slug: 'scentcap',
    name: 'ScentCap',
    symbol: '◌',
    category: 'Lifestyle',
    ver: '2.1.0',
    tagline: 'Your fragrance collection, and what to wear today.',
    pitch: 'Catalog bottles, log wears, and pick for today — wardrobe on your device.',
    hook: 'The wardrobe that remembers what you wore.',
    accent: '#c9a87c',
    accent2: '#8b6914',
    bg: '#1a1614',
    vibe: 'luxury',
    demo: true,
    url: 'https://shamikhahmed.github.io/ScentCap/',
    pitchUrl: 'https://shamikhahmed.github.io/ScentCap/pitch.html',
    github: 'https://github.com/shamikhahmed/ScentCap',
    icon: 'assets/icons/scentcap.svg',
    mark: 'assets/marks/scentcap.svg',
    screenshot: 'assets/screenshots/scentcap.png',
    highlights: ['Wardrobe', 'Today', 'Wear log', 'Layering'],
    features: ['Today picks from your wardrobe', 'Bottle catalog + levels', 'Wear log', 'Rules-based advisor — not cloud AI'],
  },
  {
    slug: 'soulcap',
    name: 'SoulCap',
    symbol: '✧',
    category: 'Wellness',
    ver: '8.2.0',
    tagline: 'Quiet tools to steady yourself. Not therapy.',
    pitch: 'Check-ins, techniques, and journal on your device. Not therapy, not a crisis service.',
    hook: 'Steady yourself quietly. Your journal stays on your phone.',
    accent: '#7c6ff7',
    accent2: '#a78bfa',
    bg: '#0f0f1a',
    vibe: 'soul',
    demo: true,
    url: 'https://shamikhahmed.github.io/SoulCap/',
    pitchUrl: 'https://shamikhahmed.github.io/SoulCap/pitch.html',
    github: 'https://github.com/shamikhahmed/SoulCap',
    icon: 'assets/icons/soulcap.svg',
    mark: 'assets/marks/soulcap.svg',
    screenshot: 'assets/screenshots/soulcap.png',
    highlights: ['Check-in', 'Techniques', 'Journal', 'Help'],
    features: ['One-tap check-in', 'Guided techniques', 'On-device journal', 'Region-aware help numbers'],
  },
  {
    slug: 'travelcap',
    name: 'TravelCap',
    symbol: '✈',
    category: 'Travel',
    ver: '1.0.0',
    tagline: 'Trips, tickets and travel documents in one place.',
    pitch: 'Trips, packing, transit, and documents — local-first travel organizer.',
    hook: 'Before, during, after — every mile on your device.',
    accent: '#007aff',
    accent2: '#38bdf8',
    bg: '#051a33',
    vibe: 'travel',
    demo: true,
    url: 'https://shamikhahmed.github.io/TravelCap/',
    pitchUrl: 'https://shamikhahmed.github.io/TravelCap/',
    github: 'https://github.com/shamikhahmed/TravelCap',
    icon: 'assets/icons/travelcap.svg',
    mark: 'assets/marks/travelcap.svg',
    screenshot: 'assets/screenshots/travelcap.png',
    highlights: ['Trips', 'Documents', 'Packing', 'Offline'],
    features: ['Trip dashboard', 'Transit and stays', 'Document vault', 'Always check official sources for visas and flights'],
  },
  {
    slug: 'auracap',
    name: 'AuraCap',
    symbol: '◎',
    category: 'Productivity',
    ver: '5.4.0',
    tagline: 'Organize your iPhone, iPad and Mac setup.',
    pitch: 'Import your app list, score your setup, and organize across devices — nothing uploaded.',
    hook: 'Your Apple setup at a glance. Stored only on this device.',
    accent: '#4f6ef7',
    accent2: '#7b5ea7',
    bg: '#050507',
    vibe: 'apple',
    demo: true,
    url: 'https://shamikhahmed.github.io/AuraCap/',
    pitchUrl: 'https://shamikhahmed.github.io/AuraCap/pitch.html',
    github: 'https://github.com/shamikhahmed/AuraCap',
    icon: 'assets/icons/auracap.svg',
    mark: 'assets/marks/auracap.svg',
    screenshot: 'assets/screenshots/auracap.png',
    highlights: ['Overview', 'Setup report', 'Aura Score', 'Organize'],
    features: ['Overview of your setup', 'Setup report from your app list', 'Aura Score with Focus · Clarity · Organization', 'Not affiliated with Apple'],
  },
  {
    slug: 'masterycap',
    name: 'MasteryCap',
    symbol: '▣',
    category: 'Education',
    ver: '51.9.0',
    tagline: 'Learn trading and software step by step, in English or Roman Urdu.',
    pitch: 'Bilingual learning tracks with quizzes and practice — educational, not financial advice.',
    hook: 'Learn step by step. No income promises.',
    accent: '#7cffb2',
    accent2: '#2a9d6a',
    bg: '#070a08',
    vibe: 'school',
    demo: true,
    url: 'https://shamikhahmed.github.io/MasteryCap/',
    pitchUrl: 'https://github.com/shamikhahmed/MasteryCap',
    github: 'https://github.com/shamikhahmed/MasteryCap',
    icon: 'assets/icons/masterycap.svg',
    mark: 'assets/marks/masterycap.svg',
    screenshot: 'assets/screenshots/masterycap.png',
    highlights: ['Bilingual', 'Tracks', 'Quizzes', 'Practice'],
    features: ['English and Roman Urdu tracks', 'Quizzes and spaced practice', 'Self-issued certificates only', 'Nothing here is financial advice'],
  },
  {
    slug: 'ideacap',
    name: 'IdeaCap',
    symbol: '✦',
    category: 'Productivity',
    ver: '2.0.0',
    tagline: 'Capture ideas by voice or text. They stay on your device.',
    pitch: 'Voice and text idea capture. Your notes stay on your device.',
    hook: 'Capture now. Find later. Nothing leaves your phone.',
    accent: '#f5c542',
    accent2: '#c4921a',
    bg: '#070b1a',
    vibe: 'idea',
    demo: true,
    url: 'https://shamikhahmed.github.io/IdeaCap/',
    pitchUrl: 'https://shamikhahmed.github.io/IdeaCap/',
    github: 'https://github.com/shamikhahmed/IdeaCap',
    icon: 'assets/icons/ideacap.svg',
    mark: 'assets/marks/ideacap.svg',
    screenshot: 'assets/screenshots/ideacap.png',
    highlights: ['Voice', 'Text', 'On device', 'Summary'],
    features: ['Voice and text capture', 'Ideas board on device', 'Summary without cloud AI by default', 'Optional keys only if you add them'],
  },
  {
    slug: 'carcap',
    name: 'CarCap',
    symbol: '▣',
    category: 'Lifestyle',
    ver: '1.0.0',
    tagline: 'Service, fuel and documents for your cars.',
    pitch: 'Garage, service logs, fuel, and documents — on your phone.',
    hook: 'Your cars on your phone. No dealer cloud.',
    accent: '#ff6b4a',
    accent2: '#c43d22',
    bg: '#0c0908',
    vibe: 'car',
    demo: true,
    url: 'https://shamikhahmed.github.io/CarCap/',
    pitchUrl: 'https://shamikhahmed.github.io/CarCap/',
    github: 'https://github.com/shamikhahmed/CarCap',
    icon: 'assets/icons/carcap.svg',
    mark: 'assets/marks/carcap.svg',
    screenshot: 'assets/screenshots/carcap.png',
    highlights: ['Garage', 'Service', 'Fuel', 'Docs'],
    features: ['Multi-vehicle garage', 'Service log and coming-up reminders', 'Fuel and odometer', 'Documents on device'],
  },
  {
    slug: 'cookcap',
    name: 'CookCap',
    symbol: '◌',
    category: 'Home',
    ver: '3.5.0',
    tagline: 'Your family cookbook, kept like a real book.',
    pitch: 'Family recipes, cook mode, and shopping list — feels like a real book.',
    hook: 'Recipes your family actually cooks. On your device.',
    accent: '#c4784a',
    accent2: '#8b4513',
    bg: '#1a120e',
    vibe: 'cook',
    demo: true,
    url: 'https://shamikhahmed.github.io/CookCap/',
    pitchUrl: 'https://shamikhahmed.github.io/CookCap/',
    github: 'https://github.com/shamikhahmed/CookCap',
    icon: 'assets/icons/cookcap.svg',
    mark: 'assets/marks/cookcap.svg',
    screenshot: 'assets/screenshots/travelcap.png',
    highlights: ['Recipes', 'Cook mode', 'Shopping', 'Family'],
    features: ['Family cookbook cover', 'Cook mode', 'Shopping list', 'Nutrition estimates only'],
  },
  {
    slug: 'deefoodie',
    name: 'DeeFoodie',
    symbol: '◎',
    category: 'Food',
    ver: '1.0.0+3',
    tagline: 'A private journal of where you eat in Karachi.',
    pitch: 'Private beta — a journal of Karachi eats for invited devices only.',
    hook: 'Your Karachi. Private beta.',
    accent: '#e8c27a',
    accent2: '#1a2e1f',
    bg: '#0f1a14',
    vibe: 'food',
    privateBeta: true,
    wip: true,
    url: '',
    pitchUrl: '',
    github: '',
    icon: 'assets/icons/deefoodie.svg',
    mark: 'assets/marks/deefoodie.svg',
    screenshot: '',
    highlights: ['Private beta', 'Karachi', 'Journal'],
    features: ['Private beta — no public install link', 'Visit journal with photos', 'Sync across your devices', 'Delete my data in Settings'],
  },
];

export function wipBadgeHTML() {
  return '<span class="wip-badge">WIP</span>';
}

export function privateBetaBadgeHTML() {
  return '<span class="wip-badge">Private beta</span>';
}

/** Capricorn OS task list — desktop Tasks widget + iOS Today (single source). */
export const TASKS = [
  { label: 'Follow on GitHub', tag: 'Connect', detail: '@shamikhahmed', action: 'social', social: 'github' },
  { label: 'Open VaultCap', tag: 'VaultCap', detail: 'Private vault', action: 'app', slug: 'vaultcap' },
  { label: 'Open PulseCap', tag: 'PulseCap', detail: 'Train offline', action: 'app', slug: 'pulsecap' },
  { label: 'Open LedgerCap', tag: 'LedgerCap', detail: 'PSX ledger', action: 'app', slug: 'ledgercap' },
  { label: 'Open SteadyCap', tag: 'SteadyCap', detail: 'Recovery', action: 'app', slug: 'steadycap' },
  { label: 'Open PrismCap', tag: 'PrismCap', detail: 'Party games', action: 'app', slug: 'prismcap' },
  { label: 'Open DeePonyCap', tag: 'DeePonyCap', detail: 'Collection', action: 'app', slug: 'deeponycap' },
  { label: 'Open ScentCap', tag: 'ScentCap', detail: 'Wear log', action: 'app', slug: 'scentcap' },
  { label: 'Open SoulCap', tag: 'SoulCap', detail: 'Steady yourself', action: 'app', slug: 'soulcap' },
  { label: 'Open AuraCap', tag: 'AuraCap', detail: 'Apple setup', action: 'app', slug: 'auracap' },
  { label: 'Open CarCap', tag: 'CarCap', detail: 'Garage', action: 'app', slug: 'carcap' },
  { label: 'Open MasteryCap', tag: 'MasteryCap', detail: 'Learn', action: 'app', slug: 'masterycap' },
  { label: 'Open TravelCap', tag: 'TravelCap', detail: 'Trips', action: 'app', slug: 'travelcap' },
  { label: 'Open IdeaCap', tag: 'IdeaCap', detail: 'Ideas', action: 'app', slug: 'ideacap' },
  { label: 'Open CookCap', tag: 'CookCap', detail: 'Cookbook', action: 'app', slug: 'cookcap' },
];

export const SYSTEM = {
  name: 'Capricorn OS',
  version: '1.0.0',
  build: 'hub-tier1-2026-09-15',
  founder: 'Shamikh Ahmed',
  tagline: 'Software that lives on your device.',
  pitch: 'Capricorn Systems builds Cap apps that live on your phone — encrypted on your device, no cloud rent, no analytics. Capricorn OS is the hub.',
  logo: 'assets/logo.svg',
};

/** Social accounts — only entries with a live `url` */
export const SOCIAL = [
  { id: 'github', label: 'GitHub', handle: '@shamikhahmed', url: 'https://github.com/shamikhahmed' },
].filter((s) => s.url && String(s.url).trim());
